https://discourse.onlinedegree.iitm.ac.in/t/164277

The update being that the evaluation.py file was provided so that you could test your code against it.</p>
<p>Thanks for bringing it to our attention.</p>
<p>Kind regards</p><hr>

<h4>23f2000983 (#89)</h4>
<aside class="quote group-faculty" data-post="1" data-topic="164277" data-username="s.anand">
<div class="title">
<div class="quote-controls"></div>
 s.anand:</div>
<blockquote>
<p><strong>Update: 27 Feb 2025</strong>:</p>
</blockquote>
</aside>
<p>Sir, does this mean 27th is submission deadline?</p><hr>

<h4>23f2000237 (#88)</h4>
<p>Today’s 9th Feb and it’s a Sunday.</p><hr>

<h4>22f2001640 (#86)</h4>
<p><a class="mention" href="/u/s.anand">@s.anand</a> <a class="mention" href="/u/carlton">@carlton</a> <a class="mention" href="/u/jivraj">@Jivraj</a><br/>
<strong>I am getting below error message from LLM end points <strong><a href="https://api.openai.com/v1/chat/completions" rel="noopener nofollow ugc">https://api.openai.com/v1/chat/completions</a> or <a href="https://aiproxy.sanand.workers.dev/openai/v1/embeddings" rel="noopener nofollow ugc">https://aiproxy.sanand.workers.dev/openai/v1/embeddings</a></strong> , while running my project .</strong></p>
<p><br/>
Kindly help me to resolve this issue.