https://discourse.onlinedegree.iitm.ac.in/t/171141

But the current datagen.py script fails as error propagates to main, where it is not handled and causes abnormal termination without executing the functions for creating files for A9 and A10 as well.</p>
<p>Thank you.<br/>
Regards,<br/>
Shivaditya</p><hr>

<h4>24ds3000090 (#431)</h4>
<p>Dear Sirs,<br/>
<a class="mention" href="/u/jivraj">@Jivraj</a> <a class="mention" href="/u/saransh_saini">@Saransh_Saini</a> <a class="mention" href="/u/carlton">@carlton</a></p>
<p>As per the Project 1 deliverables, I had submitted my Docker Hub repo, that hosted the Docker image.