https://discourse.onlinedegree.iitm.ac.in/t/171141

That’s why It didn’t pass Prechecks</p><hr>

<h4>Jivraj (#231)</h4>
<p>This was mistake from our end we rectified it and reevaluated your submission.<br/>
Your submission has a good score.</p><hr>

<h4>Jivraj (#230)</h4>
<p>Dockerfile has to be insider root directory of github repo.</p><hr>

<h4>23f2005702 (#229)</h4>
<p><a class="mention" href="/u/carlton">@carlton</a> <a class="mention" href="/u/jivraj">@Jivraj</a> <a class="mention" href="/u/saransh_saini">@Saransh_Saini</a><br/>
Can you pls tell me my project 1 marks<br/>
My evaluation.py had 2 score<br/>
First one 1/20 where every task showed error second one had 10/20…</p><hr>

<h4>Jivraj (#228)</h4>
<p>Hi <a class="mention" href="/u/aryantikam">@AryanTikam</a></p>
<p>I looked at your github repo, You have used python’s <code>openai</code> module for doing project1, but AIPROXY_TOKEN is supposed to be used through anand sir’s proxy.</p><hr>

<h4>AryanTikam (#227)</h4>
<p>Yes except B1 somehow.</p><hr>

<h4>carlton (#226)</h4>
<p>Did all tasks produce the same error?</p><hr>

<h4>AryanTikam (#225)</h4>
<p><div class="lightbox-wrapper"><a class="lightbox" data-download-href="/uploads/short-url/f8POUeYUc14WP3S01hUZIrrPUOW.png?dl=1" href="https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/6/a/6a204d9c51d90a584e4e56d593b24821129e056e.png" rel="noopener nofollow ugc" title="1000004190"><div class="meta"><svg aria-hidden="true" class="fa d-icon d-icon-far-image svg-icon"><use href="#far-image"></use></svg><span class="filename">1000004190</span><span class="informations">1193×1149 136 KB</span><svg aria-hidden="true" class="fa d-icon d-icon-discourse-expand svg-icon"><use href="#discourse-expand"></use></svg></div></a></div><br/>
Here it is with the task, however the error doesn’t seem to be related to the task itself based on the returned message in the JSON.